1.
public class Main{
    public static void main(String[] args) {
    
    int numero=10;
    int numero1=5;
    
    System.out.println("La suma de los numero es: " +(numero+numero1));
    System.out.println("La resta de los numeros es:" +(numero-numero1));
    System.out.println("La multiplicacion de los numeros es: " +(numero*numero1));
    System.out.println("La division de los numeros es: "+(numero/numero1));
}
}

2.
public class Main{
    public static void main(String[] args) {
    
    int a=50;
    int b=5;
    int g=0;
    
    if(a>=b){
        
        if(a==b){
            System.out.println("El numero A y B son iguales");
        }
        else{
            System.out.println("El numero A es mayor al numero B");
        }
    }
    else{
    System.out.println("El numero B es mayor al numero A");
    }
}
}
